Repository codestates-seb/seb39_main_049, pull requests merged in 2022-09, with the labels that each got.

#8 server deploy test
  .DS_Store
  server/appspec.yml
  server/buildspec.yml
  server/scripts/initialize.sh
  server/scripts/server_clear.sh
  server/scripts/server_start.sh
  server/scripts/server_stop.sh
  server/src/main/java/server/controller/TestController.java
Labels: deploy, backend

#12 Create PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: planning

#16 Feat: Add Cors configuration
  server/src/main/java/server/ServerApplication.java
Labels: fix, backend

#13 Update README.md
  README.md
Labels: [FE]박인후

#27 Feat : Zustand 설치 및 Counter 예제
  client/.gitignore
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/Counter.js
  client/src/index.js
  client/src/pages/PostPage.js
  client/src/pages/index.js
  client/src/redux/index.js
  client/src/redux/reducers/couterSlice.js
  client/src/redux/reducers/index.js
  client/src/redux/store/index.js
  client/src/store/store.js
  client/src/utils/useAxios.js
Labels: feature, frontend, [FE]박인후

#28 일반 회원가입 기능 구현
  server/src/main/java/server/ServerApplication.java
  server/src/main/java/server/audit/Auditable.java
  server/src/main/java/server/controller/TestController.java
  server/src/main/java/server/user/controller/UserController.java
  server/src/main/java/server/user/dto/UserPostDto.java
  server/src/main/java/server/user/dto/UserResponseDto.java
  server/src/main/java/server/user/entity/User.java
  server/src/main/java/server/user/mapper/UserMapper.java
  server/src/main/java/server/user/repository/UserRepository.java
  server/src/main/java/server/user/service/UserService.java
  server/src/main/resources/application.properties
  server/src/main/resources/application.yml
Labels: feature, backend

#33 Component/avatar wrapper
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/assets/images/bronze.png
  client/src/assets/images/daia.png
  client/src/assets/images/gold.png
  client/src/assets/images/platinum.png
  client/src/assets/images/silver.png
  client/src/assets/styles/GlobalStyle.js
  client/src/components/Answer.js
  client/src/components/AvatarWrapper.js
  client/src/pages/PostPage.js
  client/src/reportWebVitals.js
  client/src/store/store.js
Labels: fix, frontend, [FE]박인후

#35 Feat/post page
  client/package-lock.json
  client/package.json
  client/src/components/Answer.js
Labels: feature, frontend, [FE]박인후

#32 Question CRUD 구현
  server/build.gradle
  server/src/main/java/server/question/controller/QuestionController.java
  server/src/main/java/server/question/dto/QuestionPostPutDto.java
  server/src/main/java/server/question/dto/QuestionResponseDto.java
  server/src/main/java/server/question/dto/QuestionsResponseDto.java
  server/src/main/java/server/question/entity/Question.java
  server/src/main/java/server/question/mapper/QuestionMapper.java
  server/src/main/java/server/question/repository/QuestionRepository.java
  server/src/main/java/server/question/service/QuestionService.java
  server/src/main/java/server/response/MultiResponseDto.java
  server/src/main/java/server/response/PageInfo.java
  server/src/main/java/server/user/controller/UserController.java
  server/src/main/java/server/user/dto/UserPostDto.java
  server/src/main/java/server/user/dto/UserPutDto.java
  server/src/main/java/server/user/entity/User.java
Labels: feature, backend

#41 Feat/main page
  client/src/App.js
  client/src/components/Carousel.js
  client/src/components/Header.js
  client/src/components/QuestionCard.js
  client/src/components/QuestionCards.js
  client/src/components/Tagbox.js
  client/src/pages/MainPage.js
  client/src/pages/PostPage.js
  client/src/reportWebVitals.js
Labels: feature, frontend

#46 Feat/main page
  client/src/components/Header.js
Labels: feature, frontend

#47 Feat/modal
  client/src/App.js
  client/src/components/Answer.js
  client/src/components/Header.js
  client/src/components/SignIn.js
  client/src/components/SignInModal.js
  client/src/components/SignUp.js
  client/src/pages/PostPage.js
  client/src/store/store.js
Labels: feature, frontend, [FE]박인후

#44 Feat/entity mapping & create responseDto
  server/src/main/java/server/answer/controller/AnswerController.java
  server/src/main/java/server/answer/dto/AnswerResponseDto.java
  server/src/main/java/server/answer/entity/Answer.java
  server/src/main/java/server/answer/mapper/AnswerMapper.java
  server/src/main/java/server/answer/repository/AnswerRepository.java
  server/src/main/java/server/answer/service/AnswerService.java
  server/src/main/java/server/comment/controller/CommentController.java
  server/src/main/java/server/comment/dto/CommentResponseDto.java
  server/src/main/java/server/comment/entity/Comment.java
  server/src/main/java/server/comment/mapper/CommentMapper.java
  server/src/main/java/server/comment/repository/CommentRepository.java
  server/src/main/java/server/comment/service/CommentService.java
  server/src/main/java/server/question/controller/QuestionController.java
  server/src/main/java/server/question/dto/QuestionResponseDto.java
  server/src/main/java/server/question/dto/QuestionsResponseDto.java
  server/src/main/java/server/question/entity/Question.java
  server/src/main/java/server/question/mapper/QuestionMapper.java
  server/src/main/java/server/user/dto/UserProfileResponseDto.java
  server/src/main/java/server/user/dto/UserResponseDto.java
  server/src/main/java/server/user/entity/User.java
  server/src/main/java/server/user/mapper/UserMapper.java
Labels: feature, backend

#51 Root에 gitignore 파일 추가
  .DS_Store
  .gitignore
  client/.nvmrc
  client/src/components/SignIn.js
  client/src/components/SignInModal.js
  client/src/utils/axiosInstance.js
  client/src/utils/axiosRequest.js
  client/src/utils/useAxios.js
Labels: backend, frontend

#50 [FE] Feat : 로고 누를시 MianPage로 이동, 카드 누를시 PostPage로 이동.
  client/src/App.js
  client/src/components/Header.js
  client/src/components/QuestionCard.js
  client/src/components/SignInModal.js
Labels: feature, frontend

#53 SignUp Validation check
  client/package-lock.json
  client/package.json
  client/src/components/SignInModal.js
  client/src/components/SignUp.js
  client/src/utils/delay.js
Labels: feature, frontend, [FE]박인후

#54 loginId 제거
  server/src/main/java/server/user/dto/UserPostDto.java
  server/src/main/java/server/user/dto/UserPutDto.java
  server/src/main/java/server/user/dto/UserResponseDto.java
  server/src/main/java/server/user/entity/User.java
  server/src/main/java/server/user/repository/UserRepository.java
  server/src/main/java/server/user/service/UserService.java
Labels: backend

#61 Feat/sign up axios.post 구현
  client/src/components/SignInModal.js
  client/src/components/SignUp.js
  client/src/utils/axiosRequest.js
  server/src/main/java/server/user/dto/UserPostDto.java
  server/src/main/java/server/user/dto/UserPutDto.java
  server/src/main/java/server/user/dto/UserResponseDto.java
  server/src/main/java/server/user/entity/User.java
  server/src/main/java/server/user/repository/UserRepository.java
  server/src/main/java/server/user/service/UserService.java
Labels: feature, frontend, [FE]박인후

#63 Merge
  client/src/utils/useAxios.js
  server/build.gradle
  server/src/main/java/server/ServerApplication.java
  server/src/main/java/server/exception/ExceptionCode.java
  server/src/main/java/server/jwt/config/SecurityConfig.java
  server/src/main/java/server/jwt/controller/RefreshTokenController.java
  server/src/main/java/server/jwt/filter/JwtAuthenticationFilter.java
  server/src/main/java/server/jwt/filter/JwtAuthorizationFilter.java
  server/src/main/java/server/jwt/oauth/PrincipalDetails.java
  server/src/main/java/server/jwt/oauth/PrincipalDetailsService.java
  server/src/main/java/server/user/dto/TokenResponseDto.java
  server/src/main/java/server/user/entity/RefreshToken.java
  server/src/main/java/server/user/repository/RefreshTokenRepository.java
  server/src/main/java/server/user/service/UserService.java
Labels: feature, backend

#59 feat: answers 페이지네이션 적용
  server/src/main/java/server/answer/mapper/AnswerMapper.java
  server/src/main/java/server/answer/repository/AnswerRepository.java
  server/src/main/java/server/answer/service/AnswerService.java
  server/src/main/java/server/question/controller/QuestionController.java
  server/src/main/java/server/question/dto/QuestionResponseDto.java
  server/src/main/java/server/question/mapper/QuestionMapper.java
  server/src/main/java/server/user/dto/UserPostDto.java
  server/src/main/java/server/user/dto/UserPutDto.java
Labels: feature, backend

#64 Feat : SignIn axios Post 구현
  client/src/components/SignIn.js
  client/src/components/SignInModal.js
  client/src/components/SignUp.js
  client/src/utils/axiosRequest.js
Labels: feature, frontend, [FE]박인후

#67 Refactor: 컨트롤러 메서드별 로그인 사용자 정보 적용
  server/src/main/java/server/answer/controller/AnswerController.java
  server/src/main/java/server/answer/entity/Answer.java
  server/src/main/java/server/comment/controller/CommentController.java
  server/src/main/java/server/jwt/filter/JwtAuthorizationFilter.java
  server/src/main/java/server/question/controller/QuestionController.java
  server/src/main/java/server/question/dto/ViewsDto.java
  server/src/main/java/server/question/service/QuestionService.java
  server/src/main/java/server/user/controller/UserController.java
  server/src/main/java/server/user/dto/PasswordDto.java
  server/src/main/java/server/user/repository/UserRepository.java
  server/src/main/java/server/user/service/UserService.java
Labels: backend

#74 refactor: postman 테스트 후 일부 코드 수정
  server/src/main/java/server/jwt/config/SecurityConfig.java
  server/src/main/java/server/jwt/filter/JwtAuthorizationFilter.java
  server/src/main/java/server/user/dto/UserProfileResponseDto.java
  server/src/main/java/server/user/dto/UserPutDto.java
  server/src/main/java/server/user/dto/UserResponseDto.java
  server/src/main/java/server/user/mapper/UserMapper.java
  server/src/main/java/server/user/service/UserService.java
Labels: backend, refactor

#69 Feat/get questions
  client/src/components/QuestionCard.js
  client/src/components/QuestionCards.js
  client/src/pages/MainPage.js
  client/src/store/store.js
  client/src/utils/axiosRequest.js
Labels: feature, frontend, [FE]박인후

#75 Feat/ getAnswers, getComments
  client/src/App.js
  client/src/assets/images/index.js
  client/src/components/Answer.js
  client/src/components/QuestionCard.js
  client/src/components/QuestionCards.js
  client/src/pages/PostPage.js
  client/src/store/store.js
  client/src/utils/axiosRequest.js
  client/src/utils/useAxios.js
Labels: feature, frontend, [FE]박인후

#76 application.yml & build.gradle 수정
  server/build.gradle
  server/src/main/resources/application-local.yml
  server/src/main/resources/application-server.yml
  server/src/main/resources/application.yml
Labels: backend

#77 Dev->main
  client/src/App.js
  client/src/assets/images/index.js
  client/src/components/Answer.js
  client/src/components/Header.js
  client/src/components/QuestionCard.js
  client/src/components/QuestionCards.js
  client/src/components/SignIn.js
  client/src/components/SignInModal.js
  client/src/components/SignUp.js
  client/src/pages/MainPage.js
  client/src/pages/PostPage.js
  client/src/pages/QuestionPostPage.js
  client/src/store/store.js
  client/src/utils/axiosRequest.js
  server/build.gradle
  server/src/main/java/server/ServerApplication.java
  server/src/main/java/server/answer/controller/AnswerController.java
  server/src/main/java/server/answer/entity/Answer.java
  server/src/main/java/server/answer/mapper/AnswerMapper.java
  server/src/main/java/server/answer/repository/AnswerRepository.java
  server/src/main/java/server/answer/service/AnswerService.java
  server/src/main/java/server/comment/controller/CommentController.java
  server/src/main/java/server/exception/ExceptionCode.java
  server/src/main/java/server/jwt/config/SecurityConfig.java
  server/src/main/java/server/jwt/controller/RefreshTokenController.java
  server/src/main/java/server/jwt/filter/JwtAuthenticationFilter.java
  server/src/main/java/server/jwt/filter/JwtAuthorizationFilter.java
  server/src/main/java/server/jwt/oauth/PrincipalDetails.java
  server/src/main/java/server/jwt/oauth/PrincipalDetailsService.java
  server/src/main/java/server/question/controller/QuestionController.java
  server/src/main/java/server/question/dto/QuestionResponseDto.java
  server/src/main/java/server/question/dto/ViewsDto.java
  server/src/main/java/server/question/mapper/QuestionMapper.java
  server/src/main/java/server/question/service/QuestionService.java
  server/src/main/java/server/user/controller/UserController.java
  server/src/main/java/server/user/dto/PasswordDto.java
  server/src/main/java/server/user/dto/TokenResponseDto.java
  server/src/main/java/server/user/dto/UserPostDto.java
  server/src/main/java/server/user/dto/UserProfileResponseDto.java
  server/src/main/java/server/user/dto/UserPutDto.java
  server/src/main/java/server/user/entity/RefreshToken.java
  server/src/main/java/server/user/entity/User.java
  server/src/main/java/server/user/mapper/UserMapper.java
  server/src/main/java/server/user/repository/RefreshTokenRepository.java
  server/src/main/java/server/user/repository/UserRepository.java
  server/src/main/java/server/user/service/UserService.java
  server/src/main/resources/application-local.yml
  server/src/main/resources/application-server.yml
  server/src/main/resources/application.yml
Labels: backend, frontend

#82 Feat/question post page
  client/src/App.js
  client/src/components/BasicButton.js
  client/src/components/Header.js
  client/src/components/QuestionInfoSelect.js
  client/src/pages/QuestionPostPage.js
  client/src/store/store.js
Labels: feature, frontend

#85 fix/etc
  server/HELP.md
  server/gradlew
  server/gradlew.bat
  server/src/main/java/server/jwt/filter/JwtAuthenticationFilter.java
  server/src/main/java/server/user/repository/RefreshTokenRepository.java
  server/src/main/java/server/user/repository/UserRepository.java
  server/src/main/java/server/user/service/UserService.java
Labels: fix, backend

#89 Question 에 대한 조회수 구현
  client/package-lock.json
  client/package.json
  client/src/components/Answer.js
  client/src/components/QuestionCard.js
  client/src/pages/PostPage.js
  client/src/store/store.js
  client/src/utils/auth.js
  client/src/utils/axiosInstance.js
  client/src/utils/axiosRequest.js
  client/src/utils/cookies.js
  client/src/utils/tokenAuth.js
Labels: feature, frontend, [FE]박인후

#88 fix: 유저 비밀번호 변경 시 기존 비밀번호 확인하도록 수정
  server/src/main/java/server/user/controller/UserController.java
  server/src/main/java/server/user/dto/PasswordDto.java
  server/src/main/java/server/user/service/UserService.java
Labels: fix, backend

#91 feat/ validation 예외처리
  server/src/main/java/server/answer/controller/AnswerController.java
  server/src/main/java/server/answer/dto/VotesDto.java
  server/src/main/java/server/comment/controller/CommentController.java
  server/src/main/java/server/comment/dto/CommentPostPutDto.java
  server/src/main/java/server/exception/ErrorResponse.java
  server/src/main/java/server/exception/GlobalExceptionAdvice.java
  server/src/main/java/server/question/controller/QuestionController.java
  server/src/main/java/server/question/dto/ViewsDto.java
  server/src/main/java/server/user/controller/UserController.java
  server/src/main/java/server/user/dto/UserPostDto.java
  server/src/main/java/server/user/dto/UserPutDto.java
  server/src/main/java/server/user/service/UserService.java
Labels: feature, backend

#100 Hotfix
  server/src/main/java/server/jwt/config/SecurityConfig.java
  server/src/main/java/server/jwt/filter/JwtAuthenticationFilter.java
  server/src/main/java/server/question/repository/QuestionRepository.java
  server/src/main/java/server/question/service/QuestionService.java
  server/src/main/java/server/user/repository/RefreshTokenRepository.java
Labels: fix, backend

#102 CORS 수정
  client/.eslintrc.json
  server/src/main/java/server/jwt/filter/JwtAuthenticationFilter.java
Labels: fix, backend

#95 Feat/question post page
  client/src/components/QuestionInfoSelect.js
  client/src/pages/QuestionPostPage.js
Labels: feature, frontend, refactor

#110 fix: 전체 질문 조회 시 답변 수 추가로 반환하도록 수정
  server/src/main/java/server/question/controller/QuestionController.java
  server/src/main/java/server/question/dto/QuestionsResponseDto.java
  server/src/main/java/server/question/mapper/QuestionMapper.java
Labels: fix, backend

#111 fix: cascade 삭제 및 예외처리 3종 추가
  server/src/main/java/server/answer/entity/Answer.java
  server/src/main/java/server/exception/BusinessLogicException.java
  server/src/main/java/server/exception/ErrorResponse.java
  server/src/main/java/server/exception/ExceptionCode.java
  server/src/main/java/server/exception/GlobalExceptionAdvice.java
  server/src/main/java/server/question/entity/Question.java
  server/src/main/java/server/user/entity/User.java
  server/src/main/java/server/user/service/UserService.java
Labels: fix, backend

#112 프로필 이미지 경로 수정
  client/src/components/Answer.js
  client/src/components/QuestionCards.js
  client/src/pages/PostPage.js
  client/src/store/store.js
Labels: fix, frontend, [FE]박인후

#113 refactor: 유저 활동 상태 반환, 기본 프로필 이미지 경로 지정
  server/src/main/java/server/user/dto/UserResponseDto.java
  server/src/main/java/server/user/mapper/UserMapper.java
  server/src/main/java/server/user/service/UserService.java
Labels: backend, refactor

#117 토큰관련 수정
  server/src/main/java/server/exception/ExceptionCode.java
  server/src/main/java/server/exception/GlobalExceptionAdvice.java
  server/src/main/java/server/jwt/controller/RefreshTokenController.java
  server/src/main/java/server/jwt/filter/JwtAuthorizationFilter.java
Labels: fix, backend

#118 Feat/jwt token
  client/src/utils/auth.js
  client/src/utils/axiosInstance.js
  client/src/utils/axiosRequest.js
  client/src/utils/cookies.js
  client/src/utils/tokenAuth.js
Labels: feature, frontend

#119 feat: UserInfo answers & comments 조회 기능 구현
  server/src/main/java/server/answer/controller/AnswerController.java
  server/src/main/java/server/answer/dto/AnswerUserResponseDto.java
  server/src/main/java/server/answer/mapper/AnswerMapper.java
  server/src/main/java/server/answer/repository/AnswerRepository.java
  server/src/main/java/server/answer/service/AnswerService.java
  server/src/main/java/server/comment/dto/CommentUserResponseDto.java
  server/src/main/java/server/comment/mapper/CommentMapper.java
  server/src/main/java/server/comment/repository/CommentRepository.java
  server/src/main/java/server/comment/service/CommentService.java
  server/src/main/java/server/question/controller/QuestionController.java
  server/src/main/java/server/question/mapper/QuestionMapper.java
  server/src/main/java/server/user/controller/UserController.java
  server/src/main/java/server/user/dto/UserAnswersResponseDto.java
  server/src/main/java/server/user/dto/UserCommentsResponseDto.java
  server/src/main/java/server/user/dto/UserResponseDto.java
  server/src/main/java/server/user/mapper/UserMapper.java
  server/src/main/java/server/user/service/UserService.java
Labels: feature, backend

#127 Kr/refactor
  server/src/main/java/server/answer/controller/AnswerController.java
  server/src/main/java/server/answer/service/AnswerService.java
  server/src/main/java/server/comment/controller/CommentController.java
  server/src/main/java/server/comment/service/CommentService.java
  server/src/main/java/server/exception/ExceptionCode.java
  server/src/main/java/server/jwt/filter/JwtAuthorizationFilter.java
  server/src/main/java/server/question/controller/QuestionController.java
  server/src/main/java/server/question/service/QuestionService.java
  server/src/main/java/server/response/MultiResponseDto.java
  server/src/main/java/server/user/controller/UserController.java
  server/src/main/java/server/user/service/UserService.java
Labels: fix, backend, refactor

#129 fix: 전체질문 조회 및 기타
  server/src/main/java/server/answer/controller/AnswerController.java
  server/src/main/java/server/question/controller/QuestionController.java
Labels: fix, backend

#142 Feat/jwt token
  client/src/utils/axiosRequest.js
  client/src/utils/useAxiosPrivate.js
Labels: feature, frontend

#148 refactor: 로그인 없이 작성글 조회할 수 있도록 수정
  server/src/main/java/server/user/controller/UserController.java
  server/src/main/java/server/user/mapper/UserMapper.java
Labels: backend

#149 Dev -> test-server
  client/src/utils/axiosRequest.js
  client/src/utils/useAxiosPrivate.js
  server/src/main/java/server/user/controller/UserController.java
  server/src/main/java/server/user/mapper/UserMapper.java
Labels: backend

#155 Userpage 잠정마무리(서버 변경사항 적용될때까지)
  client/src/pages/UserPage/AnswerComment.js
  client/src/pages/UserPage/UserPage.js
  client/src/utils/axiosRequest.js
Labels: feature, frontend, [FE]박인후

#157 refactor: 유저페이지 작성글 반환값 수정
  server/src/main/java/server/answer/dto/AnswerUserResponseDto.java
  server/src/main/java/server/answer/mapper/AnswerMapper.java
  server/src/main/java/server/answer/service/AnswerService.java
  server/src/main/java/server/comment/mapper/CommentMapper.java
  server/src/main/java/server/comment/service/CommentService.java
  server/src/main/java/server/response/AnswerCommentUserResponseDto.java
  server/src/main/java/server/user/dto/UserAnswersResponseDto.java
  server/src/main/java/server/user/dto/UserCommentsResponseDto.java
  server/src/main/java/server/user/mapper/UserMapper.java
Labels: backend

#158 TagBox 제작
  client/src/components/QuestionCard.js
  client/src/components/Tab/CategoryTabs.js
  client/src/components/Tagbox.js
  client/src/pages/MainPage.js
  client/src/pages/UserPage/UserPage.js
Labels: feature, frontend, [FE]박인후

#160 fix: 킬-실행 slepp 10에서 15로 수정
  server/scripts/deploy.sh
Labels: fix, deploy, backend

#167 Feat : MyPage 완료
  client/src/components/Answer.js
  client/src/components/SignIn.js
  client/src/components/Tab/BasicTabs.js
  client/src/components/UserDropdown.js
  client/src/pages/MainPage.js
  client/src/pages/PostPage.js
  client/src/pages/UserPage/AnswerComment.js
  client/src/pages/UserPage/UserPage.js
  client/src/store/store.js
  client/src/utils/axiosRequest.js
  client/src/utils/cookies.js
  client/src/utils/timeHandler.js
Labels: feature, frontend, [FE]박인후

#168 Feat/sorting
  server/src/main/java/server/answer/mapper/AnswerMapper.java
  server/src/main/java/server/answer/repository/AnswerRepository.java
  server/src/main/java/server/answer/service/AnswerService.java
  server/src/main/java/server/comment/service/CommentService.java
  server/src/main/java/server/exception/ExceptionCode.java
  server/src/main/java/server/question/controller/QuestionController.java
  server/src/main/java/server/question/entity/Question.java
  server/src/main/java/server/question/mapper/QuestionMapper.java
  server/src/main/java/server/question/service/QuestionService.java
Labels: feature, backend

#170 fix: sql로그 중복출력 수정 및 추가 설정
  server/build.gradle
  server/src/main/resources/application-local.yml
  server/src/main/resources/application-main.yml
  server/src/main/resources/application-test.yml
Labels: fix, backend

#171 [FE] Refac : jwt-token 리팩토링, 코드수정, axosinterceptor 코드 수정, isLogin 상태…
  client/src/App.js
  client/src/components/Header.js
  client/src/pages/MainPage.js
  client/src/pages/UserPage/AnswerComment.js
  client/src/store/store.js
  client/src/utils/axiosRequest.js
  client/src/utils/cookies.js
  client/src/utils/useAxiosPrivate.js
Labels: frontend, refactor

#174 [FE] Answer 삭제기능 구현
  client/src/components/AlertDialog.js
  client/src/components/Answer.js
  client/src/components/Header.js
  client/src/pages/UserPage/AnswerComment.js
  client/src/pages/UserPage/UserPage.js
  client/src/utils/axiosInstance.js
  client/src/utils/axiosRequest.js
  client/src/utils/useAxiosPrivate.js
Labels: frontend, [FE]박인후

#172 feat: 질문 검색 기능 구현
  server/src/main/java/server/question/controller/QuestionController.java
  server/src/main/java/server/question/entity/Question.java
  server/src/main/java/server/question/repository/QuestionRepository.java
  server/src/main/java/server/question/service/QuestionService.java
Labels: feature, backend

#179 fix: 주석제거 및 https 추가
  server/.gitignore
  server/src/main/java/server/ServerApplication.java
  server/src/main/resources/application-test.yml
Labels: feature, fix, backend

#180 Feat/answer
  client/src/components/AnswerModal.js
  client/src/components/UserDropdown.js
  client/src/pages/PostPage.js
  client/src/pages/UserPage/UserPage.js
  client/src/store/store.js
  server/src/main/resources/application-test.yml
Labels: feature, frontend, refactor

#187 Feat/answer
  client/src/api/post.js
  client/src/components/AnswerModal.js
  client/src/components/SignIn.js
  client/src/pages/QuestionPostPage.js
  client/src/utils/axiosRequest.js
  client/src/utils/useAxiosPrivate.js
  server/src/main/resources/application-test.yml
Labels: feature, frontend
