Repository codestates-seb/seb39_main_049, pull requests merged in 2022-10, with the labels that each got.

#188 [FE] Feat : Category별 Get 기능 구현
  client/src/components/Pagination.js
  client/src/components/QuestionCard.js
  client/src/components/QuestionCards.js
  client/src/components/Tab/CategoryTabs.js
  client/src/components/Tab/Tagbox.js
  client/src/pages/MainPage.js
  client/src/store/store.js
Labels: feature, frontend, [FE]박인후

#189 메인 페이지 질문 조회 시 카테고리 필터링 및 정렬 방법 변경
  server/src/main/java/server/question/controller/QuestionController.java
  server/src/main/java/server/question/repository/QuestionRepository.java
  server/src/main/java/server/question/service/QuestionService.java
Labels: fix, backend, refactor

#192 [FE] Feat : updateVotes 구현
  client/src/components/Answer.js
  client/src/components/Pagination.js
  client/src/components/QuestionCards.js
  client/src/pages/MainPage.js
  client/src/pages/PostPage.js
  client/src/pages/UserPage/UserPage.js
  client/src/store/store.js
  client/src/utils/axiosRequest.js
Labels: feature, frontend, [FE]박인후

#191 feat: 중복추천 방지 추가
  server/src/main/java/server/answer/controller/AnswerController.java
  server/src/main/java/server/answer/entity/Vote.java
  server/src/main/java/server/answer/repository/VoteRepository.java
  server/src/main/java/server/answer/service/AnswerService.java
  server/src/main/java/server/exception/ExceptionCode.java
Labels: fix, backend

#194 MainPage 및 PostPage 조회수,추천수,최신순 등록
  client/src/api/put.js
  client/src/components/Answer.js
  client/src/components/Header.js
  client/src/components/QuestionCards.js
  client/src/components/UserDropdown.js
  client/src/pages/MainPage.js
  client/src/pages/PostPage.js
  client/src/store/store.js
  client/src/utils/axiosRequest.js
Labels: frontend, [FE]박인후

#195 postpage UI 개선
  client/src/components/Answer.js
  client/src/components/AnswerEditModal.js
  client/src/components/AnswerModal.js
  client/src/pages/PostPage.js
Labels: feature, frontend

#196 [FE] Refactor
  client/src/components/Answer.js
  client/src/components/AnswerEditModal.js
  client/src/components/Pagination.js
  client/src/components/QuestionCard.js
  client/src/components/QuestionCards.js
  client/src/components/Tab/Tagbox.js
  client/src/pages/MainPage.js
  client/src/pages/UserPage/UserPage.js
Labels: frontend, [FE]박인후, refactor

#198 Fix/category
  client/src/App.js
  client/src/pages/MainPage/MainPage.js
  client/src/pages/MainPage/QuestionCard.js
  client/src/pages/MainPage/QuestionCards.js
Labels: bug, fix, [FE]박인후

#199 feat: 카테고리 관련 구직데이터 크롤링 v1
  server/build.gradle
  server/src/main/java/server/ServerApplication.java
  server/src/main/java/server/crawling/CrawlingScheduler.java
  server/src/main/java/server/crawling/entity/Recruit.java
  server/src/main/java/server/crawling/repository/RecruitRepository.java
Labels: feature, backend

#201 fix: 데이터 갱신시 이전 데이터 삭제처리
  server/src/main/java/server/crawling/CrawlingScheduler.java
Labels: fix, backend

#200 Comment Post 구현, 페이지네이션 구현
  client/src/api/post.js
  client/src/components/Answer.js
  client/src/components/AnswerEditModal.js
  client/src/components/AnswerModal.js
  client/src/components/UserDropdown.js
  client/src/pages/PostPage.js
  client/src/store/store.js
  client/src/utils/axiosRequest.js
Labels: feature, frontend, refactor

#207 feat: 유저 점수 추가
  server/src/main/java/server/answer/controller/AnswerController.java
  server/src/main/java/server/answer/service/AnswerService.java
  server/src/main/java/server/comment/controller/CommentController.java
  server/src/main/java/server/comment/service/CommentService.java
  server/src/main/java/server/user/controller/UserController.java
  server/src/main/java/server/user/dto/UserResponseDto.java
  server/src/main/java/server/user/entity/Badge.java
  server/src/main/java/server/user/entity/User.java
  server/src/main/java/server/user/mapper/UserMapper.java
  server/src/main/java/server/user/repository/BadgeRepository.java
  server/src/main/java/server/user/service/UserService.java
Labels: feature, backend

#208 이메일 발송 기능 구현
  server/build.gradle
  server/src/main/java/server/email/controller/EmailController.java
  server/src/main/java/server/email/dto/EmailPostDto.java
  server/src/main/java/server/email/dto/EmailResponseDto.java
  server/src/main/java/server/email/entity/EmailMessage.java
  server/src/main/java/server/email/service/EmailService.java
  server/src/main/java/server/user/service/UserService.java
  server/src/main/resources/application-main.yml
  server/src/main/resources/application-test.yml
  server/src/main/resources/templates/email.html
  server/src/main/resources/templates/password.html
Labels: feature, backend

#210 fix: 로그인 및 인증 ErrorResponse 추가
  server/src/main/java/server/crawling/CrawlingScheduler.java
  server/src/main/java/server/exception/ExceptionCode.java
  server/src/main/java/server/jwt/config/SecurityConfig.java
  server/src/main/java/server/jwt/filter/JwtAuthorizationFilter.java
  server/src/main/java/server/jwt/handler/UserAuthenticationFailureHandler.java
  server/src/main/java/server/jwt/oauth/PrincipalDetailsService.java
  server/src/main/resources/application-local.yml
Labels: fix, backend

#216 fix: 좋아요 권한처리 수정
  server/src/main/java/server/jwt/config/SecurityConfig.java
Labels: fix, backend

#220 Feat/search
  client/src/api/put.js
  client/src/components/AnswerEditModal.js
  client/src/components/CommentEditForm.js
  client/src/components/SearchForm.js
  client/src/components/Tab/CategoryTabs.js
  client/src/components/Tab/Tagbox.js
  client/src/pages/MainPage/MainPage.js
  client/src/pages/MainPage/QuestionCards.js
  client/src/pages/MainPage/SearchedQuestionCards.js
  client/src/store/store.js
  client/src/utils/axiosRequest.js
Labels: feature, frontend

#223 Refactoring 예시
  client/src/api/Answer/index.js
  client/src/api/Answer/post.js
  client/src/api/post.js
  client/src/components/AnswerModal.js
Labels: frontend, refactor

#222 feat: 대용량 데이터 조회 속도 개선
  server/src/main/java/server/crawling/dto/RecruitDto.java
  server/src/main/java/server/crawling/repository/RecruitRepository.java
  server/src/main/java/server/crawling/service/RecruitService.java
  server/src/test/java/server/crawling/RecruitServiceTest.java
Labels: feature, backend, refactor

#224 Refactor/directory
  client/.eslintrc.json
  client/package-lock.json
  client/package.json
  client/src/api/Answer/delete.js
  client/src/api/Answer/index.js
  client/src/api/Answer/post.js
  client/src/api/Answer/put.js
  client/src/api/Answer/votes.js
  client/src/api/Comment/delete.js
  client/src/api/Comment/index.js
  client/src/api/Comment/post.js
  client/src/api/Comment/put.js
  client/src/api/Question/index.js
  client/src/api/Question/post.js
  client/src/api/User/activity.js
  client/src/api/User/index.js
  client/src/api/User/logout.js
  client/src/api/User/modify.js
  client/src/api/User/refresh.js
  client/src/api/User/signIn.js
  client/src/api/User/signUp.js
  client/src/api/put.js
  client/src/components/AnswerEditModal.js
  client/src/components/CommentEditForm.js
  client/src/components/SignIn.js
  client/src/components/SignUp.js
  client/src/components/UserDropdown.js
  client/src/pages/PostPage/Answer.js
  client/src/pages/QuestionPostPage.js
  client/src/pages/UserPage/ModifyUserPage.js
  client/src/pages/UserPage/ProfileModal.js
  client/src/pages/UserPage/UserInfoPage.js
  client/src/pages/UserPage/UserPage.js
  client/src/store/store.js
  client/src/utils/axiosInstance.js
  client/src/utils/axiosRequest.js
Labels: [FE]박인후, refactor

#225 fix: 공통세팅 분류
  server/src/main/resources/application-local.yml
  server/src/main/resources/application-main.yml
  server/src/main/resources/application-test.yml
  server/src/main/resources/application.yml
Labels: fix, backend

#226 Refactor/error handling
  client/src/api/Answer/delete.js
  client/src/api/Answer/votes.js
  client/src/api/Question/post.js
  client/src/api/User/signIn.js
  client/src/api/User/signUp.js
  client/src/components/SearchForm.js
  client/src/components/SignIn.js
  client/src/components/SignUp.js
  client/src/components/Tab/Tagbox.js
  client/src/pages/MainPage/MainPage.js
  client/src/pages/MainPage/QuestionCards.js
  client/src/pages/QuestionPostPage.js
  client/src/pages/UserPage/UserInfoPage.js
  client/src/utils/axiosInstance.js
Labels: frontend, [FE]박인후, refactor

#231 [FE] Style : 브라우저에서 볼 때 이름 변경
  client/public/index.html
  client/src/components/Header.js
  client/src/components/Tab/Tagbox.js
Labels: frontend, [FE]박인후

#234 질문 등록 후 폼 리셋.
  client/src/api/Comment/post.js
  client/src/pages/PostPage/Answer.js
  client/src/pages/QuestionPostPage.js
  client/src/store/store.js
Labels: frontend, refactor

#237 refactor: 필드에러와 일반 에러 형식 통일
  server/src/main/java/server/exception/ErrorResponse.java
  server/src/main/java/server/exception/GlobalExceptionAdvice.java
Labels: fix, backend, refactor

#239 페이지 이동시 최상단으로 이동하도록 구현.
  client/src/App.js
  client/src/api/Answer/post.js
  client/src/api/Question/post.js
  client/src/components/AnswerModal.js
  client/src/components/Pagination.js
  client/src/components/ScrollToTop.js
  client/src/index.js
  client/src/pages/QuestionPostPage.js
Labels: feature, frontend, refactor

#240 회원탈퇴기능 추가
  client/src/api/User/delete.js
  client/src/api/User/index.js
  client/src/components/Tab/UserTab.js
  client/src/store/store.js
Labels: feature, frontend, [FE]박인후

#241 [FE] Refactor : UI
  client/src/App.js
  client/src/components/Pagination.js
  client/src/components/ScrollToTopButton.js
  client/src/components/Tab/CategoryTabs.js
  client/src/components/Tab/Tagbox.js
  client/src/index.js
  client/src/pages/MainPage/MainPage.js
  client/src/pages/MainPage/QuestionCard.js
  client/src/utils/ScrollToTop.js
  client/src/utils/timeHandler.js
Labels: frontend, [FE]박인후, refactor

#236 UserControllerTest 작성 및 구직 api 추가
  server/build.gradle
  server/src/main/java/server/crawling/CrawlingScheduler.java
  server/src/main/java/server/crawling/controller/RecruitController.java
  server/src/main/java/server/crawling/dto/RecruitResponseDto.java
  server/src/main/java/server/crawling/mapper/RecruitMapper.java
  server/src/main/java/server/crawling/repository/RecruitRepository.java
  server/src/main/java/server/crawling/service/RecruitService.java
  server/src/main/java/server/user/dto/PasswordDto.java
  server/src/main/java/server/user/dto/UserDto.java
  server/src/main/java/server/user/dto/UserPostDto.java
  server/src/test/java/server/user/controller/UserControllerTest.java
Labels: backend, test

#247 [FE] Refactoring : 에러핸들링 수정
  client/src/App.js
  client/src/api/Answer/delete.js
  client/src/api/Answer/post.js
  client/src/api/Answer/votes.js
  client/src/api/Comment/post.js
  client/src/api/Question/post.js
  client/src/api/User/delete.js
  client/src/api/User/logout.js
  client/src/api/User/signIn.js
  client/src/api/User/signUp.js
  client/src/components/AnswerModal.js
  client/src/components/SignIn.js
  client/src/components/SignUp.js
  client/src/pages/PostPage/Answer.js
  client/src/pages/PostPage/QuestionPostPage.js
  client/src/utils/axiosInstance.js
Labels: frontend, [FE]박인후, refactor

#252 [FE] Refactor : 로그인 모달내부 버튼 스타일 변경, 메인페이지 select,search 레이아웃 변경
  client/src/components/SearchForm.js
  client/src/components/SignInModal.js
  client/src/components/Tab/Tagbox.js
  client/src/pages/MainPage/MainPage.js
Labels: frontend, refactor

#254 TagBox,CategoryTabs 관련 수정
  .github/workflows/front-dev.yml
  client/public/index.html
  client/src/components/Tab/CategoryTabs.js
  client/src/components/Tab/Tagbox.js
  client/src/pages/MainPage/Carousel/Carousel.js
  client/src/pages/PostPage/Answer.js
  client/src/pages/UserPage/ModifyUserPage.js
Labels: frontend, [FE]박인후, refactor

#264 채용공고 추가
  client/src/api/Employ/get.js
  client/src/api/Employ/index.js
  client/src/components/Pagination.js
  client/src/components/SearchForm.js
  client/src/components/Tab/BasicTabs.js
  client/src/components/Tab/Tagbox.js
  client/src/components/Tab/UserTab.js
  client/src/pages/MainPage/Carousel/Carousel.js
  client/src/pages/MainPage/EmployAnnouncement.js
  client/src/pages/MainPage/MainPage.js
  client/src/pages/MainPage/QuestionCards.js
  client/src/pages/MainPage/SearchedQuestionCards.js
Labels: feature, frontend, [FE]박인후
